name: Production CI

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  production-export:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Modules
        run: yarn
      - name: Build
        run: yarn export:production
