name: "CLA Signature Bot"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  CLABot:
    if: github.event_name == 'pull_request_target' || contains(github.event.comment.html_url, '/pull/')
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Signature Bot"
        uses: MetaMask/cla-signature-bot@v3.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: "cla-signatures.json"
          url-to-cladocument: "https://github.com/newswap/newswap-web/blob/dev-web/cla.md"
          # This branch can't have protections, commits are made directly to the specified branch.
          branch: "cla-signatures"
          allowlist: ""
          allow-organization-members: false
          blockchain-storage-flag: false
